services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: spotify_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: spotify_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres:
    image: postgres:13
    container_name: spotify_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_DB=spotify_db
      - PGTZ=Asia/Kolkata
    ports:
      - "5432:5432"
    command: >                     
      postgres
      -c TimeZone=Asia/Kolkata

  grafana:
    image: grafana/grafana:10.4.0
    container_name: spotify_grafana
    ports:
      - "3000:3000"
    depends_on:
      - postgres